### ISSUE TITLE
alpha-dust instead of landscape

### ISSUE THREAD

**Issue by phicarre** [klugjo/hexo-theme-alpha-dust#7]
Hello,
I tried to add your theme in my site (instead of landscape). I only change the name of the theme in the _config.yml file:
Here are my first errors:

`Unhandled rejection TypeError: /home/jpc/hexo-project/themes/alpha-dust/layout/page.ejs:8
    6| 
    7|         <section class="main">
 >> 8|             <%- partial('_partial/article-long', {item: page}) %>
    9|         </section>
    10|     </div>
    11| </div>

/home/jpc/hexo-project/themes/alpha-dust/layout/_partial/article-long.ejs:11
    9|         </h1>
    10|         <div class="post-info">
 >> 11|             <span class="date"><%= item.date.format(config.date_format) %></span>
    12|             <a href="#disqus_thread" class="comments"><%= __('comment') %></a>
    13|             <% if(item.categories && item.categories.first()) { %>
    14|                 <span class="category">

Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:415)
    at eval (eval at <anonymous> (/home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:547)
    at /home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jpc/hexo-project/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jpc/hexo-project/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jpc/hexo-project/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jpc/hexo-project/node_modules/hexo/node_modules/lodash/lodash.js:4762:19)
    at eval (eval at <anonymous> (/home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:263)
    at eval (eval at <anonymous> (/home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:360)
    at /home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jpc/hexo-project/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jpc/hexo-project/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jpc/hexo-project/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/jpc/hexo-project/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/jpc/hexo-project/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/jpc/hexo-project/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:733:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
`
I believe that your theme cannot be used "as is" ;-)

**Comment by klugjo** [comment]
You are right, this is a bug

It looks like you have a page or post that does not have a date set up

**Comment by phicarre** [comment]
you are right also ! a date was missing in draft file.
thank you.

**Comment by klugjo** [comment]
should be good now. Closing this ticket for now, let me know if the problem still occurs

cheers

**Comment by phicarre** [comment]
```
Unhandled rejection TypeError: /home/jpc/hexo-project/themes/alpha-dust/layout/page.ejs:8
    6| 
    7|         <section class="main">
 >> 8|             <%- partial('_partial/article-long', {item: page}) %>
    9|         </section>
    10|     </div>
    11| </div>

/home/jpc/hexo-project/themes/alpha-dust/layout/_partial/article-long.ejs:11
    9|         </h1>
    10|         <div class="post-info">
 >> 11|             <span class="date"><%= item.date.format(config.date_format) %></span>
    12|             <a href="#disqus_thread" class="comments"><%= __('comment') %></a>
    13|             <% if(item.categories && item.categories.first()) { %>
    14|                 <span class="category">
Cannot read property 'format' of undefined
    at eval (eval at <anonymous> (/home/jpc/hexo-project/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:415)

```
